LaMiaPizzeriaWebApi/Models/Pizza.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace LaMiaPizzeriaWebApi.Models
{
    public class Pizza
    {
        public int Id { get; set; }

        [Column(TypeName = "varchar(100)")]
        [StringLength(100, ErrorMessage = "Il campo titolo non può contenere più di 100 caratteri")]
        public string Name { get; set; }

        [Column(TypeName = "text")]
        public string Description { get; set; }

        [Column(TypeName = "varchar(300)")]
        [StringLength(300, ErrorMessage = "Il campo titolo non può contenere più di 300 caratteri")]
        public string Image { get; set; }


        public double Price { get; set; }


        public bool Favorites { get; set; }

        public int? CategoryId { get; set; }
        public Category? Category { get; set; }

        public List<Ingrediente>?Ingredienti { get; set; }


        public Pizza() { }

        public Pizza(string name, string description, string image, double price, bool favorites)
        {
            this.Name = name;
            this.Description = description;
            this.Image = image;
            this.Price = price;
            this.Favorites = favorites;

        }

    }
}

LaMiaPizzeriaWebApi/Models/PizzaView.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LaMiaPizzeriaWebApi.Models
{
    public class PizzaView
    {
        public Pizza Pizze { get; set; }

        public List<Category>? Categories { get; set; }

        public List<SelectListItem>? Ingredienti { get; set; }

       
        public List<string>? TagsSelectedFromMultipleSelect { get; set; }
    }
}

LaMiaPizzeriaWebApi/Controllers/PizzaController.cs
using LaMiaPizzeriaWebApi.Database;
using LaMiaPizzeriaWebApi.Models;
using LaMiaPizzeriaWebApi.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;

namespace LaMiaPizzeriaWebApi.Controllers
{
    public class PizzaController : Controller
    {
        public IActionResult Index()
        {
            using (PizzaContext db = new PizzaContext())
            {
                List<Pizza> listaDellePizze = db.Pizze.ToList<Pizza>();
                return View("Index", listaDellePizze);
            }
        }

        public IActionResult Details(int id)
        {
            using (PizzaContext db = new PizzaContext())
            {
                // LINQ: syntax methos
                Pizza pizzaTrovata = db.Pizze
                    .Where(SingolaPizzaNelDb => SingolaPizzaNelDb.Id == id)
                    .Include(pizza => pizza.Category)
                    .Include(pizza => pizza.Ingredienti)
                    .FirstOrDefault();

                if (pizzaTrovata != null)
                {
                    return View(pizzaTrovata);
                }

                return NotFound("La pizza con l'id cercato non esiste!");

            }

        }

        [HttpGet]
        public IActionResult Create()
        {
            using (PizzaContext db = new PizzaContext())
            {
                List<Category> categoriesFromDb = db.Categories.ToList<Category>();

                PizzaView modelForView = new PizzaView();
                modelForView.Pizze = new Pizza();

                modelForView.Categories = categoriesFromDb;
                modelForView.Ingredienti = IngredientiConverter.getListIngredientiForMultipleSelect();

                return View("Create", modelForView);
            }


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PizzaView formData)
        {
            if (!ModelState.IsValid)
            {
                using (PizzaContext db = new PizzaContext())
                {
                    List<Category> categories = db.Categories.ToList<Category>();
                    formData.Categories = categories;


                    formData.Ingredienti = IngredientiConverter.getListIngredientiForMultipleSelect();
                }


                return View("Create", formData);
            }

            using (PizzaContext db = new PizzaContext())
            {
                if (formData.TagsSelectedFromMultipleSelect != null)
                {
                    formData.Pizze.Ingredienti = new List<Ingrediente>();

                    foreach (string ingredienteId in formData.TagsSelectedFromMultipleSelect)
                    {
                        int ingredienteIdIntFromSelect = int.Parse(ingredienteId);

                        Ingrediente ingredienti = db.ingredienti.Where(ingredientiDb => ingredientiDb.Id == ingredienteIdIntFromSelect).FirstOrDefault();

                        // todo controllare eventuali altri errori tipo l'id del tag non esiste

                        formData.Pizze.Ingredienti.Add(ingredienti);
                    }
                }

                db.Pizze.Add(formData.Pizze);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Update(int id)
        {
            using (PizzaContext db = new PizzaContext())
            {
                Pizza pizzaToUpdate = db.Pizze.Where(pizza => pizza.Id == id).Include(pizza => pizza.Ingredienti).FirstOrDefault();

                if (pizzaToUpdate == null)
                {
                    return NotFound("La pizza non è stata trovata");
                }

                List<Category> categories = db.Categories.ToList<Category>();

                PizzaView modelForView = new PizzaView();
                modelForView.Pizze = pizzaToUpdate;
                modelForView.Categories = categories;


                List<Ingrediente> listIngredientiFromDb = db.ingredienti.ToList<Ingrediente>();

                List<SelectListItem> listaOpzioniPerLaSelect = new List<SelectListItem>();

                foreach (Ingrediente ingredienti in listIngredientiFromDb)
                {
                    // Ricerco se il tag che sto inserindo nella lista delle opzioni della select era già stato selezionato dall'utente
                    // all'interno della lista dei tag del post da modificare
                    bool eraStatoSelezionato = pizzaToUpdate.Ingredienti.Any(ingredientiSelezionati => ingredientiSelezionati.Id == ingredienti.Id);

                    SelectListItem opzioneSingolaSelect = new SelectListItem() { Text = ingredienti.Title, Value = ingredienti.Id.ToString(), Selected = eraStatoSelezionato };
                    listaOpzioniPerLaSelect.Add(opzioneSingolaSelect);
                }

                modelForView.Ingredienti = listaOpzioniPerLaSelect;

                return View("Update", modelForView);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, PizzaView formData)
        {
            if (!ModelState.IsValid)
            {
                
                using (PizzaContext db = new PizzaContext())
                {
                    List<Category> categories = db.Categories.ToList<Category>();

                    formData.Categories = categories;
                }

                return View("Update", formData);
            }

            using (PizzaContext db = new PizzaContext())
            {
                Pizza pizzaToUpdate = db.Pizze.Where(pizza => pizza.Id == id).Include(pizza => pizza.Ingredienti).FirstOrDefault();

                if (pizzaToUpdate != null)
                {

                    pizzaToUpdate.Name = formData.Pizze.Name;
                    pizzaToUpdate.Description = formData.Pizze.Description;
                    pizzaToUpdate.Image = formData.Pizze.Image;
                    pizzaToUpdate.Price= formData.Pizze.Price;
                    pizzaToUpdate.Favorites= formData.Pizze.Favorites;
                    pizzaToUpdate.CategoryId = formData.Pizze.CategoryId;

                    // rimuoviamo gli ingredienti e inseriamo i nuovi
                    pizzaToUpdate.Ingredienti.Clear();

                    if (formData.TagsSelectedFromMultipleSelect != null)
                    {

                        foreach (string ingredientiId in formData.TagsSelectedFromMultipleSelect)
                        {
                            int ingredientiIdIntFromSelect = int.Parse(ingredientiId);

                            Ingrediente ingrediente = db.ingredienti.Where(ingredienteDb => ingredienteDb.Id == ingredientiIdIntFromSelect).FirstOrDefault();

                            // todo controllare eventuali altri errori tipo l'id del tag non esiste

                            pizzaToUpdate.Ingredienti.Add(ingrediente);
                        }
                    }

                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    return NotFound("La pizza che volevi modificare non è stata trovata!");
                }
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            using (PizzaContext db = new PizzaContext())
            {
                Pizza pizzaToDelete = db.Pizze.Where(pizza => pizza.Id == id).FirstOrDefault();

                if (pizzaToDelete != null)
                {
                    db.Pizze.Remove(pizzaToDelete);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    return NotFound("La pizza da eliminare non è stata trovata!");
                }
            }
        }



    }
}

LaMiaPizzeriaWebApi/Views/Pizza/Create.cshtml
@model PizzaView

<div class="container">
    <form asp-controller="Pizza" asp-action="Create" method="post">
        @Html.AntiForgeryToken()
        <div class="mb-3">
            <label>Titolo:</label>
            <input asp-for="Pizze.Name" type="text" class="form-control" />
            <span asp-validation-for="Pizze.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Descrizione:</label>
            <textarea asp-for="Pizze.Description" rows="10" class="d-block w-100"></textarea>
            <span asp-validation-for="Pizze.Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Categoria:</label>
            <select asp-for="Pizze.CategoryId" rows="10" class="d-block w-100">
                <option value=""></option>
                @foreach (Category category in Model.Categories)
                {
                    <option value="@category.Id">@category.Name</option>
                }
            </select>
            <span asp-validation-for="Pizze.CategoryId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Tag:</label>
            <select asp-for="TagsSelectedFromMultipleSelect" asp-items="@Model.Ingredienti" multiple size="10" class="form-control mb-2 mr-sm-2 ml-sm-3 leftList">
            </select>
        </div>
        <div class="mb-3 form-check">
            <label>Path Immagine:</label>
            <input asp-for="Pizze.Image" type="text" class="form-control" />
            <span asp-validation-for="Pizze.Image" class="text-danger"></span>
        </div>
        <div class="mb-3 form-check">
            <label>Prezzo:</label>
            <input asp-for="Pizze.Price" type="text" class="form-control" />
            <span asp-validation-for="Pizze.Price" class="text-danger"></span>
        </div>
        <div class="mb-3 form-check">
            <label>Tra i preferiti (True/False):</label>
            <input asp-for="Pizze.Favorites" type="text" class="form-control" />
            <span asp-validation-for="Pizze.Favorites" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary">Salva</button>
    </form>
</div>

LaMiaPizzeriaWebApi/Views/Pizza/Update.cshtml
@model PizzaView

<div class="container">
    <form asp-controller="Pizza" asp-action="Update" asp-route-id="@Model.Pizze.Id" method="post">
        @Html.AntiForgeryToken()
        <div class="mb-3">
            <label>Id:</label>
            <input asp-for="Pizze.Id" type="text" class="form-control" disabled />
        </div>
        <div class="mb-3">
            <label>Titolo:</label>
            <input asp-for="Pizze.Name" type="text" class="form-control" />
            <span asp-validation-for="Pizze.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Descrizione:</label>
            <textarea asp-for="Pizze.Description" rows="10" class="d-block w-100"></textarea>
            <span asp-validation-for="Pizze.Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Categoria:</label>
            <select asp-for="Pizze.CategoryId" rows="10" class="d-block w-100">
                <option value=""></option>
                @foreach (Category category in Model.Categories)
                {
                    <option value="@category.Id">@category.Name</option>
                }
            </select>
            <span asp-validation-for="Pizze.CategoryId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Ingredienti:</label>
            <select asp-for="TagsSelectedFromMultipleSelect" asp-items="@Model.Ingredienti" multiple size="10" class="form-control mb-2 mr-sm-2 ml-sm-3 leftList">
            </select>
        </div>
        <div class="mb-3 form-check">
            <label>Path Immagine:</label>
            <input asp-for="Pizze.Image" type="text" class="form-control" />
            <span asp-validation-for="Pizze.Image" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Prezzo:</label>
            <textarea asp-for="Pizze.Price" rows="10" class="d-block w-100"></textarea>
            <span asp-validation-for="Pizze.Price" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Tra i preferiti (True/False):</label>
            <textarea asp-for="Pizze.Favorites" rows="10" class="d-block w-100"></textarea>
            <span asp-validation-for="Pizze.Favorites" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Salva Modifiche al Post</button>
    </form>
</div>