LaMiaPizzeriaWebApi/Controllers/HomeController.cs
using LaMiaPizzeriaWebApi.Database;
using LaMiaPizzeriaWebApi.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LaMiaPizzeriaWebApi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {

            using (PizzaContext db = new PizzaContext())
            {
                List<Pizza> listaDellePizze = db.Pizze.ToList<Pizza>();
                return View( listaDellePizze);
            }

        }

        public IActionResult Lista()
        {

            return View();

        }

        public IActionResult Details()
        {
            return View();
        }







        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LaMiaPizzeriaWebApi/Controllers/PizzeController.cs
using LaMiaPizzeriaWebApi.Database;
using LaMiaPizzeriaWebApi.Models;
using LaMiaPizzeriaWebApi.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;

namespace LaMiaPizzeriaWebApi.Controllers
{
    public class PizzeController : Controller
    {
        public IActionResult Index()
        {
            using (PizzaContext db = new PizzaContext())
            {
                List<Pizza> listaDellePizze = db.Pizze.ToList<Pizza>();
                return View("Index", listaDellePizze);
            }
        }

        public IActionResult Details(int id)
        {
            using (PizzaContext db = new PizzaContext())
            {
                // LINQ: syntax methos
                Pizza pizzaTrovata = db.Pizze
                    .Where(SingolaPizzaNelDb => SingolaPizzaNelDb.Id == id)
                    .Include(pizza => pizza.Category)
                    .Include(pizza => pizza.Ingredienti)
                    .FirstOrDefault();

                if (pizzaTrovata != null)
                {
                    return View(pizzaTrovata);
                }

                return NotFound("La pizza con l'id cercato non esiste!");

            }

        }

        [HttpGet]
        public IActionResult Create()
        {
            using (PizzaContext db = new PizzaContext())
            {
                List<Category> categoriesFromDb = db.Categories.ToList<Category>();

                PizzaView modelForView = new PizzaView();
                modelForView.Pizze = new Pizza();

                modelForView.Categories = categoriesFromDb;
                modelForView.Ingredienti = IngredientiConverter.getListIngredientiForMultipleSelect();

                return View("Create", modelForView);
            }


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PizzaView formData)
        {
            if (!ModelState.IsValid)
            {
                using (PizzaContext db = new PizzaContext())
                {
                    List<Category> categories = db.Categories.ToList<Category>();
                    formData.Categories = categories;


                    formData.Ingredienti = IngredientiConverter.getListIngredientiForMultipleSelect();
                }


                return View("Create", formData);
            }

            using (PizzaContext db = new PizzaContext())
            {
                if (formData.TagsSelectedFromMultipleSelect != null)
                {
                    formData.Pizze.Ingredienti = new List<Ingrediente>();

                    foreach (string ingredienteId in formData.TagsSelectedFromMultipleSelect)
                    {
                        int ingredienteIdIntFromSelect = int.Parse(ingredienteId);

                        Ingrediente ingredienti = db.ingredienti.Where(ingredientiDb => ingredientiDb.Id == ingredienteIdIntFromSelect).FirstOrDefault();

                        // todo controllare eventuali altri errori tipo l'id del tag non esiste

                        formData.Pizze.Ingredienti.Add(ingredienti);
                    }
                }

                db.Pizze.Add(formData.Pizze);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Update(int id)
        {
            using (PizzaContext db = new PizzaContext())
            {
                Pizza pizzaToUpdate = db.Pizze.Where(pizza => pizza.Id == id).Include(pizza => pizza.Ingredienti).FirstOrDefault();

                if (pizzaToUpdate == null)
                {
                    return NotFound("La pizza non è stata trovata");
                }

                List<Category> categories = db.Categories.ToList<Category>();

                PizzaView modelForView = new PizzaView();
                modelForView.Pizze = pizzaToUpdate;
                modelForView.Categories = categories;


                List<Ingrediente> listIngredientiFromDb = db.ingredienti.ToList<Ingrediente>();

                List<SelectListItem> listaOpzioniPerLaSelect = new List<SelectListItem>();

                foreach (Ingrediente ingredienti in listIngredientiFromDb)
                {
                    // Ricerco se il tag che sto inserindo nella lista delle opzioni della select era già stato selezionato dall'utente
                    // all'interno della lista dei tag del post da modificare
                    bool eraStatoSelezionato = pizzaToUpdate.Ingredienti.Any(ingredientiSelezionati => ingredientiSelezionati.Id == ingredienti.Id);

                    SelectListItem opzioneSingolaSelect = new SelectListItem() { Text = ingredienti.Title, Value = ingredienti.Id.ToString(), Selected = eraStatoSelezionato };
                    listaOpzioniPerLaSelect.Add(opzioneSingolaSelect);
                }

                modelForView.Ingredienti = listaOpzioniPerLaSelect;

                return View("Update", modelForView);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, PizzaView formData)
        {
            if (!ModelState.IsValid)
            {
                
                using (PizzaContext db = new PizzaContext())
                {
                    List<Category> categories = db.Categories.ToList<Category>();

                    formData.Categories = categories;
                }

                return View("Update", formData);
            }

            using (PizzaContext db = new PizzaContext())
            {
                Pizza pizzaToUpdate = db.Pizze.Where(pizza => pizza.Id == id).Include(pizza => pizza.Ingredienti).FirstOrDefault();

                if (pizzaToUpdate != null)
                {

                    pizzaToUpdate.Name = formData.Pizze.Name;
                    pizzaToUpdate.Description = formData.Pizze.Description;
                    pizzaToUpdate.Image = formData.Pizze.Image;
                    pizzaToUpdate.Price= formData.Pizze.Price;
                    pizzaToUpdate.Favorites= formData.Pizze.Favorites;
                    pizzaToUpdate.CategoryId = formData.Pizze.CategoryId;

                    // rimuoviamo gli ingredienti e inseriamo i nuovi
                    pizzaToUpdate.Ingredienti.Clear();

                    if (formData.TagsSelectedFromMultipleSelect != null)
                    {

                        foreach (string ingredientiId in formData.TagsSelectedFromMultipleSelect)
                        {
                            int ingredientiIdIntFromSelect = int.Parse(ingredientiId);

                            Ingrediente ingrediente = db.ingredienti.Where(ingredienteDb => ingredienteDb.Id == ingredientiIdIntFromSelect).FirstOrDefault();

                            // todo controllare eventuali altri errori tipo l'id del tag non esiste

                            pizzaToUpdate.Ingredienti.Add(ingrediente);
                        }
                    }

                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    return NotFound("La pizza che volevi modificare non è stata trovata!");
                }
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            using (PizzaContext db = new PizzaContext())
            {
                Pizza pizzaToDelete = db.Pizze.Where(pizza => pizza.Id == id).FirstOrDefault();

                if (pizzaToDelete != null)
                {
                    db.Pizze.Remove(pizzaToDelete);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    return NotFound("La pizza da eliminare non è stata trovata!");
                }
            }
        }



    }
}

LaMiaPizzeriaWebApi/Views/Home/Details.cshtml
<div class="container">
    <div class="row">
        <div class="col-12">
            <div id="prodotto_container">
            </div>
        </div>
    </div>
</div>

@section Scripts {

    <script type="text/javascript">

        const id = window.location.href.substring(window.location.href.lastIndexOf('/') + 1);
        debugger;
        axios.get(`/api/ApiPizza/${id}`).then((res) => {
            let prodotto = res.data;
            console.log('articolo ricevuto', prodotto);


            document.getElementById('prodotto_container').innerHTML +=
                `
                            <div class="col-12 col-md-4 p-2">
                                  <div class="card post h-100">
                                        <img src="${prodotto.image}" class="card-img-top" alt="...">
                                        <div class="card-body">
                                        <h5 class="card-title">${prodotto.name}</h5>
                                                <p class="card-text">${prodotto.description}</p>
                                        </div>
                                </div>
                            </div>
                        `;

        });

    </script>
}

LaMiaPizzeriaWebApi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



@model List<Pizza>


<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link href="style.css" rel="stylesheet" />
</head>

<body>



    <div class=" pizzacon container  container-fluid text-center border-0 mt-0 mb-8  ">
        <h1 class="m-3"> Le Top Pizze </h1>

        <div class="row main row  justify-content-evenly">

            @foreach (Pizza pizza in Model)
            {
                if (pizza.Favorites == true)
                {

                    <!--Primo card-->
                    <div class="col-12 col-md-4 col-xl-4 text-dark m-3">

                        <div class="card border-0" style="width: 18rem; ">
                            <img src="@pizza.Image" class="card-img-top" alt="Pizza">
                            <div class="card-body  ">
                                <h5 class="card-title">@pizza.Name</h5>
                                <p class="card-text">@pizza.Description</p>
                                <p>@pizza.Price €</p>
                                <a class="btn btn-primary mb-3" href="@Url.Action("Details", "Pizze", new { id = @pizza.Id } )" role="button">Dettagli</a>
                            </div>
                        </div>

                    </div>

                }
            }

        </div>
    </div>





</body>

</html>

LaMiaPizzeriaWebApi/Views/Home/Lista.cshtml
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="d-flex justify-content-between align-items-center">
                <h1 class="mt-3 mb-3">Lista pizze</h1>
                <div>
                    <input id="input_search" type="text" class="form-control" placeholder="Cerca per titolo..." />
                </div>
            </div>
        </div>
    </div>
    <div id="spinner-loader" class="d-flex justify-content-center">
        <div class="spinner-border mt-5" role="status">
            <img style="width:50px;" src="https://1.bp.blogspot.com/-CAroinPVLPw/X9GYFpVZ4DI/AAAAAAABcs8/EVBG1MUGq9wj56i-HKNzi5JHpDaERVlxwCNcBGAsYHQ/s509/food_pizza_whole.png" class="sr-only" />
        </div>
    </div>
    <div id="contenitore_no_prodotti" class="row text-center d-none">
        <div class="col-12">
            <h3>Non hai inserito nessuna pizza</h3>
        </div>
    </div>
    <div id="contenitore_prodotti" class="row d-none">
        <!-- qui verranno mostrati gli elementi -->
    </div>
</div>

@section Scripts {

    <script type="text/javascript">

        loadProdotti();

        document.getElementById('input_search').addEventListener('keyup', searchProdotti);

        function searchProdotti() {
            let stringaDiRicerca = document.getElementById('input_search').value;
            loadProdotti(stringaDiRicerca);
        }

        function loadProdotti(searchString) {

            axios.get('/api/ApiPizza', {
                params: {
                    search: searchString
                }
            }
            ).then((res) => {

                console.log('risultato ok');
                console.log(res);

                debugger;

                if (res.data.length > 0) {
                    document.getElementById('contenitore_prodotti').classList.remove('d-none');
                    document.getElementById('contenitore_no_prodotti').classList.add('d-none');

                    document.getElementById('contenitore_prodotti').innerHTML = '';

                    res.data.forEach(prodotto => {

                        console.log('prodotto: ', prodotto);

                        document.getElementById('contenitore_prodotti').innerHTML +=
                            `
                                    <div class="col-12 col-md-4 p-2">
                                        <div class="card post h-100">
                                        <a href="/Home/Details/${prodotto.id}">
                                            <img src="${prodotto.image}" class="card-img-top" alt="...">
                                            <div class="card-body">
                                                <h5 class="card-title">${prodotto.name}</h5>
                                                <p class="card-text">${prodotto.description}</p>
                                            </div>
                                        </a>
                                        </div>
                                    </div>
                                    `;
                    });

                } else {

                    document.getElementById('contenitore_no_prodotti').classList.remove('d-none');
                    document.getElementById('contenitore_prodotti').classList.add('d-none');


                }

                document.getElementById('spinner-loader').classList.add('d-none');
            }).catch((error) => {
                console.log(error);
            });

        }

    </script>

}